/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface SDsColor {
    /**
    * The first name
    */
    'first': string;
    /**
    * The last name
    */
    'last': string;
    /**
    * The middle name
    */
    'middle': string;
  }
}

declare global {


  interface HTMLSDsColorElement extends Components.SDsColor, HTMLStencilElement {}
  var HTMLSDsColorElement: {
    prototype: HTMLSDsColorElement;
    new (): HTMLSDsColorElement;
  };
  interface HTMLElementTagNameMap {
    's-ds-color': HTMLSDsColorElement;
  }
}

declare namespace LocalJSX {
  interface SDsColor {
    /**
    * The first name
    */
    'first'?: string;
    /**
    * The last name
    */
    'last'?: string;
    /**
    * The middle name
    */
    'middle'?: string;
  }

  interface IntrinsicElements {
    's-ds-color': SDsColor;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      's-ds-color': LocalJSX.SDsColor & JSXBase.HTMLAttributes<HTMLSDsColorElement>;
    }
  }
}


