/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface SDsFooter {
    /**
    * The first name
    */
    'first': string;
    /**
    * The last name
    */
    'last': string;
    /**
    * The middle name
    */
    'middle': string;
  }
}

declare global {


  interface HTMLSDsFooterElement extends Components.SDsFooter, HTMLStencilElement {}
  var HTMLSDsFooterElement: {
    prototype: HTMLSDsFooterElement;
    new (): HTMLSDsFooterElement;
  };
  interface HTMLElementTagNameMap {
    's-ds-footer': HTMLSDsFooterElement;
  }
}

declare namespace LocalJSX {
  interface SDsFooter {
    /**
    * The first name
    */
    'first'?: string;
    /**
    * The last name
    */
    'last'?: string;
    /**
    * The middle name
    */
    'middle'?: string;
  }

  interface IntrinsicElements {
    's-ds-footer': SDsFooter;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      's-ds-footer': LocalJSX.SDsFooter & JSXBase.HTMLAttributes<HTMLSDsFooterElement>;
    }
  }
}


