/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface SDsHeader {
    /**
    * Header Text
    */
    'header': string;
  }
}

declare global {


  interface HTMLSDsHeaderElement extends Components.SDsHeader, HTMLStencilElement {}
  var HTMLSDsHeaderElement: {
    prototype: HTMLSDsHeaderElement;
    new (): HTMLSDsHeaderElement;
  };
  interface HTMLElementTagNameMap {
    's-ds-header': HTMLSDsHeaderElement;
  }
}

declare namespace LocalJSX {
  interface SDsHeader {
    /**
    * Header Text
    */
    'header'?: string;
  }

  interface IntrinsicElements {
    's-ds-header': SDsHeader;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      's-ds-header': LocalJSX.SDsHeader & JSXBase.HTMLAttributes<HTMLSDsHeaderElement>;
    }
  }
}


